apiVersion: v1
kind: Pod
metadata:
  name: busybox-configmap
  namespace: default
spec:
  containers:
  - name: busy-configmap
    image: busybox
    command:
      - sleep
      - "3600"
    env:
      - name: frutas
        valueFrom:
          configMapKeyRef:
            name: cores-frutas
            key: predileta

# substitua a partir de valueFrom para pegar todas as informações do arquivo ao invés de referenciar uma key específica

#    envFrom:
#    - configMapRef:
#        name: cores-frutas
