image:
  name: gcr.io/kaniko-project/executor:debug
  entrypoint: [""]

stages:
  - build

criando_imagem_container:
  stage: build
  script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"auth\":\"$(echo -n ${CI_REGISTRY_USER}:${CI_REGISTRY_PASSWORD} | base64)\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/docker-gitlab/Dockerfile --destination $CI_REGISTRY_IMAGE
  when: manual